DATA:
  USE_MOTION: True
  SIZE: 288
  TRAIN_JSON_PATH: "data2022/train_nlpaug.json"
  EVAL_JSON_PATH: "data2022/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
 


MODEL:
  NAME: "dual-stream-v2"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b2"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
  HEAD:
    CLIP_LOSS_MARGIN: 0.
    CLS_NONLINEAR: True
    CLS_LOSS_SCALE: 32
    CLS_LOSS_MARGIN: 0.35
    CAR_CLS: 'Linear'
    MO_CLS: 'Linear'
    SHARED_CLS: 'Linear'
  METRIC:
    METRIC_WEIGHT: 1.
    LOSS: 'CircleLoss'
    LOSS_SCALE: 80
    LOSS_MARGIN: 0.4
TRAIN: 
  BATCH_SIZE: 64

TEST:
  QUERY_JSON_PATH: "data2022/test-queries_nlpaug.json"
  RESTORE_FROM: "checkpoints/circle_loss.pth"

