DATA:
  USE_MOTION: True
  SIZE: 224
  TRAIN_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/train_nlpaug.json"
  EVAL_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
  
  USE_HEATMAP: False
  MULTI_FRAMES: True
  FRAMES_CONCAT: False
  NUM_FRAMES: 6
  TEXT_AUG: False


MODEL:
  NAME: "dual-text-cat-view-multi-crops"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b2"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
  SAME_TEXT: True
  MERGE_DIM: 1024
TRAIN: 
  BATCH_SIZE: 20

TEST:
  QUERY_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/test-queries_nlpaug.json"
  RESTORE_FROM: "logs/dual_baseline_multi_back/checkpoint_best_eval_multiback.pth"

