DATA:
  USE_MOTION: True
  SIZE: 224
  TRAIN_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/train_nlpaug.json"
  EVAL_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
  FRAMES_CONCAT: True
  USE_HEATMAP: True
  MULTI_FRAMES: False


MODEL:
  NAME: "dual-stream"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b2"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
TRAIN: 
  BATCH_SIZE: 22

TEST:
  QUERY_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/test-queries_nlpaug.json"
  RESTORE_FROM: "logs/single_baseline_aug1_plus_heatmap_lr0.003_freeze0_warm40_decay-80/single_baseline_aug1_plus_heatmap_best_eval.pth"
