DATA:
  USE_MOTION: True
  SIZE: 224
  TRAIN_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/train_nlpaug.json"
  EVAL_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
  FRAMES_CONCAT: False
  USE_HEATMAP: False
  USE_CLIP_FEATS: True


MODEL:
  NAME: "dual-stream"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b2"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
  EMBED_DIM: 512
  MERGE_DIM: 1024
TRAIN: 
  BATCH_SIZE: 48

TEST:
  QUERY_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/test-queries_nlpaug.json"
  RESTORE_FROM: "checkpoints/single_baseline_aug1_clipfeats.pth"

