DATA:
  USE_MOTION: True
  SIZE: 224
  TRAIN_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/train_nlpaug.json"
  EVAL_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
  FRAMES_CONCAT: False
  USE_HEATMAP: False


MODEL:
  NAME: "dual-stream-vit"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "ViT"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
TRAIN: 
  BATCH_SIZE: 32

TEST:
  QUERY_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/test-queries_nlpaug.json"
  RESTORE_FROM: "checkpoints/single_baseline_aug1_vit.pth"

