DATA:
  USE_MOTION: True
  SIZE: 288
  TRAIN_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/train_nlpaug.json"
  EVAL_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
  USE_MULTI_QUERIES: True
MODEL:
  NAME: "dual-stream-multi-queries"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b2"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
TRAIN: 
  BATCH_SIZE: 40

TEST:
  QUERY_JSON_PATH: "data/AIC23_Track2_NL_Retrieval/data/test-queries_nlpaug.json"
  RESTORE_FROM: "checkpoints/single_baseline_aug1_plus_multi_queries.pth"

