DATA:
  USE_MOTION: True
  SIZE: 288
  TRAIN_JSON_PATH: "data2022/train-tracks_nlpaug.json"
  EVAL_JSON_PATH: "data2022/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w
 


MODEL:
  NAME: "dual-stream-v2-view"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b2"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
  HEAD:
    NLP_VIEW_LOSS: 'Triplet'
    NLP_VIEW_SOFT: False
    NLP_VIEW_LOSS_MARGIN: 0.
TRAIN: 
  BATCH_SIZE: 64

TEST:
  QUERY_JSON_PATH: "data2022/test-queries_nlpaug.json"
  RESTORE_FROM: "checkpoints/view_triplet_hard.pth"

